name: esc_pos_utils
description: Basic classes for ESC/POS printing
version: 0.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_utils

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.1.2
  gbk_codec: ^0.3.2
  image: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
